[package]
name = "gently-btc"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Bitcoin block anchoring"

[dependencies]
gently-core.workspace = true
bitcoin.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
